### ISSUE TITLE
MicrosoftGesturesInstallDir environment variable not existing

### ISSUE THREAD

**Issue by YoniSmolin** [Microsoft/Gestures-Samples#1]
This case should be handled and a user-friendly comment should be displayed when the build breaks for this reason.

**Comment by mosdav** [comment]
@kfirkarmon , @YoniSmolin 
We could solve this quite easily via introducing something like common.targets.
common.targets will be included from the vc/xproj of each sample 
common.targets will include Error MSBuild task which will be evaluated to true in case MicrosoftGesturesInstallDir doesn't exist

**Comment by mosdav** [comment]
#22
