### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by Noemata** [Microsoft/Gestures-Samples#20]
Please support UWP ASAP.  Would be nice to see Microsoft as committed to UWP as Microsoft wants the rest of the world to be.  This is an important project, and it's kind of remarkable that the first public release is lacking a UWP implementation.

**Comment by YoniSmolin** [comment]
Your point is taken, @Noemata. We expect to release various UWP samples (both managed and native) in the coming days. Please stay tuned.
