### ISSUE TITLE
Linux Support for Gesture Service

### ISSUE THREAD

**Issue by prkhandelwal** [microsoft/Gestures-Samples#28]
The documentation on the repository says the .NET Core version is supported on Linux, but I couldn't find any source to download the SDK or Gesture Service for Linux. Is the .NET Core version self contained and does not require the service to be running parallel?

**Comment by YoniSmolin** [comment]
The Gesture Service must run on a Windows machine. The .Net Core sample programs in this repository are clients of the Gesture Service. You can build and run these samples on either Window or Linux. Use the host name (or ip) of the machine running the Gesture Service to tell the client which Service it should "talk" to.

Check out these lines in our [Console app](https://github.com/microsoft/Gestures-Samples/blob/master/ConsoleCore/Program.cs):

`// One can optionally pass the hostname/IP address where the gestures service is hosted`
`var gesturesServiceHostName = !args.Any() ? "localhost" : args[0];
RegisterGestures(gesturesServiceHostName).Wait();`

**Comment by prkhandelwal** [comment]
In that case, should the camera be connected to client or the host machine?

**Comment by YoniSmolin** [comment]
The camera should be connected to the host machine, the one that is running the Gestures Service.

**Comment by prkhandelwal** [comment]
Thanks for the help.. Btw is there some way to send kinect stream to the Gesture Service??

**Comment by YoniSmolin** [comment]
Yes, Kinect V2 can be used as an input device for Project Prague. This is covered in our documentation: [link1](https://docs.microsoft.com/en-us/gestures/#supported-depth-cameras), [link2](https://docs.microsoft.com/en-us/gestures/troubleshooting-kinect-camera).
