### ISSUE TITLE
Gesture Detection Stopped (Kinect V2 sensor not detected)

### ISSUE THREAD

**Issue by joelrunji** [microsoft/Gestures-Samples#30]
In a previous Win 10 build (around April 2019) gestures service and Kinect V2 could integrate seamlessly. However, following an upgrade to Win 10 (version 1903; build 18362:10024), the gestures service no longer detects Kinect V2. Kinect sensor integrates with Unity3D seamlessly. Any assistance accorded towards resolving this is highly appreciated. NB, downgrading the win build is presently not possible. Thank you.
![KinectV2ScreenShot](https://user-images.githubusercontent.com/7666251/69137496-db42a800-0af7-11ea-9875-f3d45ecc53dc.png)

**Comment by YoniSmolin** [comment]
I'll need to repro and test this locally. I don't have access to a Kinect V2 sensor this week. I will take a look next week (starting Nov. 25th).

**Comment by joelrunji** [comment]
Sure thanks @YoniSmolin . Will patiently be waiting. I think its also related to intel real sense Camera SR300 as shown by this link [https://stackoverflow.com/questions/57001753/having-troubling-connecting-sr-300-camera-in-certain-builds-of-windows](url)

**Comment by YoniSmolin** [comment]
@joelrunji, thank you for you patience.

I'm running Win 10 (version 1909; build 18363.476) and I cannot reproduce your issue (i.e., Kinect V2 works just fine with Project Prague - poses and gestures are detected successfully).

Can you please try re-installing [our software](http://aka.ms/gestures/download)? Make sure to restart your machine before you test the Gestures service.

**Comment by joelrunji** [comment]
@YoniSmolin  thank you for your suggestions and time. Unfortunately the problem still persists even after reinstalling and restarting the machine prior to testing in Win 10 (Version 2004; build 19033.1) and Win 10 (Version 1903; 18362.10024). 

I have made the following attempts too; 
- troubleshooting via the detailed [steps](https://docs.microsoft.com/en-us/gestures/troubleshooting-kinect-camera).
- reinstalling without the anti-virus.
- reinstalling Kinect SDK 2.0
 
I can also verify the depth stream is accessible via Kinect studio GUI as shown in attached file but not the Gestures service.  
The discovery client gets suspended in less than 20 seconds upon initialization as indicated by the task manager.

Would you be having other suggestions that would assist in further diagnosis? Assistance accorded is highly appreciated. 
![Kinect Image 1](https://user-images.githubusercontent.com/7666251/69820882-1e5df300-123d-11ea-96e1-b61473084121.png)
![Discovery Client](https://user-images.githubusercontent.com/7666251/69820914-32a1f000-123d-11ea-8897-f9ad5610ec5a.png)

**Comment by joelrunji** [comment]
The problem is now resolved in Win 10 (Version 2004; 19041.21) and Win 10 (Version 2004; 19041.84) after:
- Changing the default OS language settings from Chinese to English.
- Replacing the [pc's username and folder](https://www.youtube.com/watch?time_continue=6&v=w5N2aaiToiQ&feature=emb_logo) to English characters and numbers. 
- Installing the Windows intelligence update 
- Reinstalling  the Gestures service set-up
- Restarting the PC

Hopefully this will be helpful to someone
