### ISSUE TITLE
Some stock gestures and poses are internal

### ISSUE THREAD

**Issue by dzoech** [microsoft/Gestures-Samples#32]
According to https://docs.microsoft.com/en-us/dotnet/api/microsoft.gestures.stock.gestures.swipegesture?view=gestures-1.0 the SwipeGesture class should be public. But since I wasn't able to use it, I have taken a look at the assembly. Here it says the class is internal.

```
// Type: Microsoft.Gestures.Stock.Gestures.SwipeGesture
// Assembly: Microsoft.Gestures, Version=1.0.17339.1, Culture=neutral, PublicKeyToken=null
// MVID: 3B751A2D-7053-4B44-A0F0-5ACB9ECA5A0F
// Assembly location: C:\Users\dzoech\AppData\Roaming\Microsoft\Prague\PragueVersions\LatestVersion\Samples\DiscoveryClient\Microsoft.Gestures.dll
// Metadata token values is shown

using Microsoft.Gestures.Stock.HandPoses;
using System;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;

namespace Microsoft.Gestures.Stock.Gestures
{
  internal sealed class SwipeGesture : StockGesture
  {
      ...
```

Have I referenced the wrong DLL?
Also,  what's the difference between the .NET Core DLLs and the .NET Framework DLLs? Since the docs says to include the .NET Framework DLLs. Are the Core ones working nevertheless?

**Comment by YoniSmolin** [comment]
Both .Net Framework and .Net Core DLLs should provide the same functionanlity. We have [code samples](https://docs.microsoft.com/en-us/dotnet/api/microsoft.gestures.skeleton.ihandskeleton.fingerpositions?view=gestures-1.0) for both types.

You are right to note that there is ש discrepancy between the documentation and the provided library. I am sorry, but we cannot publish a new library at this time, as the project's development has been halted. Note that you can construct new gestures using the [stock hand poses](https://docs.microsoft.com/en-us/dotnet/api/microsoft.gestures.stock.handposes?view=gestures-1.0).

**Comment by dzoech** [comment]
Thank you @YoniSmolin for your help!

Is there any further public information as to how Microsoft is proceeding with any gesture recognition approaches?

Ad stock hand poses: is there any explanation how to use this base class? Which method to override for validation and how to trigger the recognition correctly?

Btw, your first link seems to be pointing to the wrong direction :)

**Comment by YoniSmolin** [comment]
I'm sorry, @dzoech, but I have no information regarding hand gesture related products by Microsoft. Consider looking into Kinect for Azure and Hololens 2 in this context.

Regarding stock hand poses, [here's an example](https://github.com/microsoft/Gestures-Samples/blob/2624bbd19be4bcb141854f871338d1d3bfe208cb/Camera3D/MainWindow.xaml.cs#L60-L62) for using them within a custom gesture. The surrounding code lines will help you figure out how to subscribe to detection events.

**Comment by dzoech** [comment]
Hello @YoniSmolin 
thanks for the further clarification. I'm really looking forward to the extended availability of the Azure Kinect DK considering the current circumstances.
