### ISSUE TITLE
Minimal distance or duration for motion

### ISSUE THREAD

**Issue by dzoech** [microsoft/Gestures-Samples#33]
Is there a possibility to define a minimum distance or duration for a HandMotion or PalmMotion?

To be specific, I'm trying to implement a swipe gesture which has no concrete ending HandPose and should only trigger if the hand is moved for at least a short distance.

**Comment by YoniSmolin** [comment]
@dzoech, I believe you can use the [palm position](https://docs.microsoft.com/en-us/dotnet/api/microsoft.gestures.skeleton.ihandskeleton.palmposition?view=gestures-1.0#Microsoft_Gestures_Skeleton_IHandSkeleton_PalmPosition) and [finger positions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.gestures.skeleton.ihandskeleton.fingerpositions?view=gestures-1.0), writing your own logic to customize a gesture for your specific temporal\spacial requirements.

**Comment by dzoech** [comment]
Am I correct in the assumption this has to be done using the GesturesServiceEndpoint.RegisterToSkeleton(...) method?

**Comment by YoniSmolin** [comment]
Yes. You can code up something along the lines of [this smoother](https://github.com/microsoft/Gestures-Samples/blob/master/Camera3D/PalmSmoother.cs) to overcome the inherent jumpiness of the raw skeleton data.
