### ISSUE TITLE
Microsoft Gestures Service does not detect any gestures

### ISSUE THREAD

**Issue by happyCodingSusan** [microsoft/Gestures-Samples#36]
I started Microsoft Gestures Service. I can see the GUI and on the GUI, I see my hands with color markers on each fingers. However, nothing is displayed under gesture, current, or timeline. Any ideas why no gestures are detected?

Many thanks for your kind reply!

**Comment by YoniSmolin** [comment]
Hi @happyCodingSusan,

Please try running one of our demo applications:

![image](https://user-images.githubusercontent.com/11846732/97268516-ac1ed580-1834-11eb-814d-1e10a4593f8f.png)

As soon as you launch an application, the GUI should be filled with detectable gestures.
